{"variants":[{"paths":["\/documentation\/mdots\/autherror\/errordescription"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"errorDescription","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"This property provides a localized description for each error case, making it easier to","type":"text"},{"type":"text","text":" "},{"type":"text","text":"understand what went wrong during the authentication process."}]}],"kind":"content"}],"abstract":[{"type":"text","text":"A description of the error, suitable for displaying to the user."}],"metadata":{"title":"errorDescription","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"errorDescription","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"symbolKind":"property","modules":[{"name":"MDots"}],"externalID":"s:5MDots9AuthErrorO16errorDescriptionSSSgvp","role":"symbol","roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/AuthError"]]},"identifier":{"url":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/AuthError\/errorDescription","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://com.estelapasjak.Mdots/documentation/MDots":{"url":"\/documentation\/mdots","kind":"symbol","abstract":[],"role":"collection","images":[{"type":"icon","identifier":"new-icon.png"}],"identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots","type":"topic","title":"MDots"},"doc://com.estelapasjak.Mdots/documentation/MDots/AuthError":{"kind":"symbol","navigatorTitle":[{"text":"AuthError","kind":"identifier"}],"title":"AuthError","type":"topic","abstract":[{"text":"An enumeration representing various authentication errors that can occur.","type":"text"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AuthError","kind":"identifier"}],"url":"\/documentation\/mdots\/autherror","identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/AuthError"},"new-icon.png":{"identifier":"new-icon.png","type":"image","alt":"The logo representing the MDot sensor application.","variants":[{"traits":["1x","light"],"url":"\/images\/new-icon.png"}]},"doc://com.estelapasjak.Mdots/documentation/MDots/AuthError/errorDescription":{"kind":"symbol","url":"\/documentation\/mdots\/autherror\/errordescription","abstract":[{"type":"text","text":"A description of the error, suitable for displaying to the user."}],"role":"symbol","identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/AuthError\/errorDescription","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorDescription","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"errorDescription"}}}